---
- name: Nginx
  hosts: ubuntu
  become: true
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Enable nginx
      service:
        name: nginx
        enabled: true
        state: started