
Vagrant.configure("2") do |config|

  config.vm.define "ubuntu_host1" do |ubuntu_host1|
    ubuntu_host1.vm.box = "ubuntu/xenial64"
    ubuntu_host1.vm.hostname = 'ubuntu-host1'
    ubuntu_host1.vm.box_url = "ubuntu/xenial64"

    ubuntu_host1.vm.network :public_network, bridge: "wlp4s0", ip: "192.168.56.101"

    ubuntu_host1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host1"]
    end
  end

  config.vm.define "ubuntu_host2" do |ubuntu_host2|
    ubuntu_host2.vm.box = "ubuntu/xenial64"
    ubuntu_host2.vm.hostname = 'ubuntu-host2'
    ubuntu_host2.vm.box_url = "ubuntu/xenial"

    ubuntu_host2.vm.network :public_network, bridge: "wlp4s0", ip: "192.168.56.102"

    ubuntu_host2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host2"]
    end
  end
end
